version: '3'

services:

  keycloak:
    image: jboss/keycloak:4.0.0.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_ADDR=keycloak-db
      - DB_PORT=3306
      - DB_DATABASE=keycloakdb
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      POSTGRES_DB: keycloakdb
    volumes:
      - pgdata:/var/lib/mysql/data

volumes:
  pgdata: